//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.07 at 08:57:59 PM AEDT 
//


package NolXml10;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The result list for a single class containing either individual results or team results.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NolClassResult", propOrder = {
    "clazz",
    "numberOfRacesToCount",
    "personResult",
    "eventList"    
})
public class NolClassResult {

    @XmlElement(name = "NolClass", required = true)
    protected String clazz;
    @XmlElement(name = "NolEventList")
    protected NolEventList eventList;
    @XmlElement(name = "NolPersonResult")
    protected List<NolPersonResult> personResult;
    @XmlElement(name = "NumberOfRacesToCount")
    protected int numberOfRacesToCount;
    //@XmlElement(name = "TeamResult")
    //protected List<NolTeamResult> teamResult;

    public int getNumberOfRacesToCount() {
        return numberOfRacesToCount;
    }

    public void setNumberOfRacesToCount(int numberOfRacesToCount) {
        this.numberOfRacesToCount = numberOfRacesToCount;
    }
    
    public String getNolClazz() {
        return clazz;
    }

    public void setNolClazz(String value) {
        this.clazz = value;
    }
    
    public NolEventList getEventList() {
        return eventList;
    }

    public void setEventList(NolEventList eventList) {
        this.eventList = eventList;
    }

    public List<NolPersonResult> getNolPersonResult() {
        if (personResult == null) {
            personResult = new ArrayList<NolPersonResult>();
        }
        return this.personResult;
    }
    
    public void setNolPersonResult(List<NolPersonResult> _personResult) {
        
        personResult= _personResult;
    }

/*    public List<NolTeamResult> getNolTeamResult() {
        if (teamResult == null) {
            teamResult = new ArrayList<NolTeamResult>();
        }
        return this.teamResult;
    }
*/


}
