//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.07 at 08:57:59 PM AEDT 
//


package NolXml10;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Result information for an individual competitor, including e.g. result status, place, finish time, and split times.
 *       
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NolPersonResult", propOrder = {
    "name",
    "team",
    "result",
})
public class NolPersonResult {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Team")
    protected String team;
    @XmlElement(name = "NolPersonRaceResult")
    protected List<NolPersonRaceResult> result;    

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getTeam() {
        return team;
    }

    public void setTeam(String team) {
        this.team = team;
    }
    
    public List<NolPersonRaceResult> getResult() {
        if (result == null) {
            result = new ArrayList<>();
        }
        return this.result;
    }

    public void setResult(List<NolPersonRaceResult> _result) {
        
        result = _result;
        
    }
}
