//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.07 at 08:57:59 PM AEDT 
//


package NolXml10;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classResult",
})
@XmlRootElement(name = "NolResultList")
public class NolResultList
    extends NolBaseMessageElement
{

    @XmlElement(name = "NolClassResult", required = true)
    protected List<NolClassResult> classResult;

    public List<NolClassResult> getNolClassResult() {
        if (classResult == null) {
            classResult = new ArrayList<NolClassResult>();
        }
        return this.classResult;
    }

    public void setNolClassResult(List<NolClassResult> _classResult) {
        
        classResult = _classResult;
    }
}
