//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.03 at 09:33:02 PM AEDT 
//


package EventorApi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EventRaceId"/>
 *         &lt;choice>
 *           &lt;element ref="{}EventId"/>
 *           &lt;element ref="{}Event"/>
 *         &lt;/choice>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}RaceDate"/>
 *         &lt;choice>
 *           &lt;element ref="{}RaceStatusId"/>
 *           &lt;element ref="{}RaceStatus"/>
 *         &lt;/choice>
 *         &lt;element ref="{}EventOfficial" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}EventCenterPosition" minOccurs="0"/>
 *         &lt;element ref="{}ModifyDate" minOccurs="0"/>
 *         &lt;element ref="{}ModifiedBy" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="raceLightCondition" default="Day">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="Day"/>
 *             &lt;enumeration value="Night"/>
 *             &lt;enumeration value="DayAndNight"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="raceDistance" default="Middle">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="Sprint"/>
 *             &lt;enumeration value="Middle"/>
 *             &lt;enumeration value="Long"/>
 *             &lt;enumeration value="UltraLong"/>
 *             &lt;enumeration value="PreO"/>
 *             &lt;enumeration value="TempO"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventRaceId",
    "eventId",
    "event",
    "name",
    "raceDate",
    "raceStatusId",
    "raceStatus",
    "eventOfficial",
    "eventCenterPosition",
    "modifyDate",
    "modifiedBy"
})
@XmlRootElement(name = "EventRace")
public class EventRace {

    @XmlElement(name = "EventRaceId", required = true)
    protected EventRaceId eventRaceId;
    @XmlElement(name = "EventId")
    protected EventId eventId;
    @XmlElement(name = "Event")
    protected Event event;
    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "RaceDate", required = true)
    protected RaceDate raceDate;
    @XmlElement(name = "RaceStatusId")
    protected RaceStatusId raceStatusId;
    @XmlElement(name = "RaceStatus")
    protected RaceStatus raceStatus;
    @XmlElement(name = "EventOfficial")
    protected List<EventOfficial> eventOfficial;
    @XmlElement(name = "EventCenterPosition")
    protected EventCenterPosition eventCenterPosition;
    @XmlElement(name = "ModifyDate")
    protected ModifyDate modifyDate;
    @XmlElement(name = "ModifiedBy")
    protected ModifiedBy modifiedBy;
    @XmlAttribute(name = "raceLightCondition")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String raceLightCondition;
    @XmlAttribute(name = "raceDistance")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String raceDistance;

    /**
     * Gets the value of the eventRaceId property.
     * 
     * @return
     *     possible object is
     *     {@link EventRaceId }
     *     
     */
    public EventRaceId getEventRaceId() {
        return eventRaceId;
    }

    /**
     * Sets the value of the eventRaceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventRaceId }
     *     
     */
    public void setEventRaceId(EventRaceId value) {
        this.eventRaceId = value;
    }

    /**
     * Gets the value of the eventId property.
     * 
     * @return
     *     possible object is
     *     {@link EventId }
     *     
     */
    public EventId getEventId() {
        return eventId;
    }

    /**
     * Sets the value of the eventId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventId }
     *     
     */
    public void setEventId(EventId value) {
        this.eventId = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link Event }
     *     
     */
    public Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link Event }
     *     
     */
    public void setEvent(Event value) {
        this.event = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the raceDate property.
     * 
     * @return
     *     possible object is
     *     {@link RaceDate }
     *     
     */
    public RaceDate getRaceDate() {
        return raceDate;
    }

    /**
     * Sets the value of the raceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link RaceDate }
     *     
     */
    public void setRaceDate(RaceDate value) {
        this.raceDate = value;
    }

    /**
     * Gets the value of the raceStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link RaceStatusId }
     *     
     */
    public RaceStatusId getRaceStatusId() {
        return raceStatusId;
    }

    /**
     * Sets the value of the raceStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RaceStatusId }
     *     
     */
    public void setRaceStatusId(RaceStatusId value) {
        this.raceStatusId = value;
    }

    /**
     * Gets the value of the raceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RaceStatus }
     *     
     */
    public RaceStatus getRaceStatus() {
        return raceStatus;
    }

    /**
     * Sets the value of the raceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RaceStatus }
     *     
     */
    public void setRaceStatus(RaceStatus value) {
        this.raceStatus = value;
    }

    /**
     * Gets the value of the eventOfficial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventOfficial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventOfficial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventOfficial }
     * 
     * 
     */
    public List<EventOfficial> getEventOfficial() {
        if (eventOfficial == null) {
            eventOfficial = new ArrayList<EventOfficial>();
        }
        return this.eventOfficial;
    }

    /**
     * Gets the value of the eventCenterPosition property.
     * 
     * @return
     *     possible object is
     *     {@link EventCenterPosition }
     *     
     */
    public EventCenterPosition getEventCenterPosition() {
        return eventCenterPosition;
    }

    /**
     * Sets the value of the eventCenterPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventCenterPosition }
     *     
     */
    public void setEventCenterPosition(EventCenterPosition value) {
        this.eventCenterPosition = value;
    }

    /**
     * Gets the value of the modifyDate property.
     * 
     * @return
     *     possible object is
     *     {@link ModifyDate }
     *     
     */
    public ModifyDate getModifyDate() {
        return modifyDate;
    }

    /**
     * Sets the value of the modifyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifyDate }
     *     
     */
    public void setModifyDate(ModifyDate value) {
        this.modifyDate = value;
    }

    /**
     * Gets the value of the modifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link ModifiedBy }
     *     
     */
    public ModifiedBy getModifiedBy() {
        return modifiedBy;
    }

    /**
     * Sets the value of the modifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifiedBy }
     *     
     */
    public void setModifiedBy(ModifiedBy value) {
        this.modifiedBy = value;
    }

    /**
     * Gets the value of the raceLightCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRaceLightCondition() {
        if (raceLightCondition == null) {
            return "Day";
        } else {
            return raceLightCondition;
        }
    }

    /**
     * Sets the value of the raceLightCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRaceLightCondition(String value) {
        this.raceLightCondition = value;
    }

    /**
     * Gets the value of the raceDistance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRaceDistance() {
        if (raceDistance == null) {
            return "Middle";
        } else {
            return raceDistance;
        }
    }

    /**
     * Sets the value of the raceDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRaceDistance(String value) {
        this.raceDistance = value;
    }

}
