//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.03 at 09:33:02 PM AEDT 
//


package EventorApi;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TimeMode_QNAME = new QName("", "TimeMode");
    private final static QName _RouteCount_QNAME = new QName("", "RouteCount");
    private final static QName _Information_QNAME = new QName("", "Information");
    private final static QName _Route_QNAME = new QName("", "Route");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TeamMemberResult }
     * 
     */
    public TeamMemberResult createTeamMemberResult() {
        return new TeamMemberResult();
    }

    /**
     * Create an instance of {@link ActivityAttribute }
     * 
     */
    public ActivityAttribute createActivityAttribute() {
        return new ActivityAttribute();
    }

    /**
     * Create an instance of {@link ActivityRegistration }
     * 
     */
    public ActivityRegistration createActivityRegistration() {
        return new ActivityRegistration();
    }

    /**
     * Create an instance of {@link ExternalLinks }
     * 
     */
    public ExternalLinks createExternalLinks() {
        return new ExternalLinks();
    }

    /**
     * Create an instance of {@link ExternalLinks.Event }
     * 
     */
    public ExternalLinks.Event createExternalLinksEvent() {
        return new ExternalLinks.Event();
    }

    /**
     * Create an instance of {@link ExternalLinks.Event.Race }
     * 
     */
    public ExternalLinks.Event.Race createExternalLinksEventRace() {
        return new ExternalLinks.Event.Race();
    }

    /**
     * Create an instance of {@link Competitor }
     * 
     */
    public Competitor createCompetitor() {
        return new Competitor();
    }

    /**
     * Create an instance of {@link CompetitorId }
     * 
     */
    public CompetitorId createCompetitorId() {
        return new CompetitorId();
    }

    /**
     * Create an instance of {@link PersonId }
     * 
     */
    public PersonId createPersonId() {
        return new PersonId();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link Family }
     * 
     */
    public Family createFamily() {
        return new Family();
    }

    /**
     * Create an instance of {@link Given }
     * 
     */
    public Given createGiven() {
        return new Given();
    }

    /**
     * Create an instance of {@link BirthDate }
     * 
     */
    public BirthDate createBirthDate() {
        return new BirthDate();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link SSN }
     * 
     */
    public SSN createSSN() {
        return new SSN();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link CountryId }
     * 
     */
    public CountryId createCountryId() {
        return new CountryId();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Alpha2 }
     * 
     */
    public Alpha2 createAlpha2() {
        return new Alpha2();
    }

    /**
     * Create an instance of {@link Alpha3 }
     * 
     */
    public Alpha3 createAlpha3() {
        return new Alpha3();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link ModifyDate }
     * 
     */
    public ModifyDate createModifyDate() {
        return new ModifyDate();
    }

    /**
     * Create an instance of {@link Clock }
     * 
     */
    public Clock createClock() {
        return new Clock();
    }

    /**
     * Create an instance of {@link ModifiedBy }
     * 
     */
    public ModifiedBy createModifiedBy() {
        return new ModifiedBy();
    }

    /**
     * Create an instance of {@link Tele }
     * 
     */
    public Tele createTele() {
        return new Tele();
    }

    /**
     * Create an instance of {@link TeleType }
     * 
     */
    public TeleType createTeleType() {
        return new TeleType();
    }

    /**
     * Create an instance of {@link Nationality }
     * 
     */
    public Nationality createNationality() {
        return new Nationality();
    }

    /**
     * Create an instance of {@link Organisation }
     * 
     */
    public Organisation createOrganisation() {
        return new Organisation();
    }

    /**
     * Create an instance of {@link OrganisationId }
     * 
     */
    public OrganisationId createOrganisationId() {
        return new OrganisationId();
    }

    /**
     * Create an instance of {@link ShortName }
     * 
     */
    public ShortName createShortName() {
        return new ShortName();
    }

    /**
     * Create an instance of {@link MediaName }
     * 
     */
    public MediaName createMediaName() {
        return new MediaName();
    }

    /**
     * Create an instance of {@link OrganisationTypeId }
     * 
     */
    public OrganisationTypeId createOrganisationTypeId() {
        return new OrganisationTypeId();
    }

    /**
     * Create an instance of {@link OrganisationType }
     * 
     */
    public OrganisationType createOrganisationType() {
        return new OrganisationType();
    }

    /**
     * Create an instance of {@link ParentOrganisationType }
     * 
     */
    public ParentOrganisationType createParentOrganisationType() {
        return new ParentOrganisationType();
    }

    /**
     * Create an instance of {@link SubOrganisationType }
     * 
     */
    public SubOrganisationType createSubOrganisationType() {
        return new SubOrganisationType();
    }

    /**
     * Create an instance of {@link ParentOrganisation }
     * 
     */
    public ParentOrganisation createParentOrganisation() {
        return new ParentOrganisation();
    }

    /**
     * Create an instance of {@link SubOrganisation }
     * 
     */
    public SubOrganisation createSubOrganisation() {
        return new SubOrganisation();
    }

    /**
     * Create an instance of {@link OrganisationOfficial }
     * 
     */
    public OrganisationOfficial createOrganisationOfficial() {
        return new OrganisationOfficial();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link RoleTypeId }
     * 
     */
    public RoleTypeId createRoleTypeId() {
        return new RoleTypeId();
    }

    /**
     * Create an instance of {@link OrganisationStatusId }
     * 
     */
    public OrganisationStatusId createOrganisationStatusId() {
        return new OrganisationStatusId();
    }

    /**
     * Create an instance of {@link OrganisationStatus }
     * 
     */
    public OrganisationStatus createOrganisationStatus() {
        return new OrganisationStatus();
    }

    /**
     * Create an instance of {@link CreateDate }
     * 
     */
    public CreateDate createCreateDate() {
        return new CreateDate();
    }

    /**
     * Create an instance of {@link MemberToDate }
     * 
     */
    public MemberToDate createMemberToDate() {
        return new MemberToDate();
    }

    /**
     * Create an instance of {@link HashTableEntry }
     * 
     */
    public HashTableEntry createHashTableEntry() {
        return new HashTableEntry();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link EventorApi.Value }
     * 
     */
    public EventorApi.Value createValue() {
        return new EventorApi.Value();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link EventId }
     * 
     */
    public EventId createEventId() {
        return new EventId();
    }

    /**
     * Create an instance of {@link EventorApi.Event }
     * 
     */
    public EventorApi.Event createEvent() {
        return new EventorApi.Event();
    }

    /**
     * Create an instance of {@link EventClassificationId }
     * 
     */
    public EventClassificationId createEventClassificationId() {
        return new EventClassificationId();
    }

    /**
     * Create an instance of {@link EventClassification }
     * 
     */
    public EventClassification createEventClassification() {
        return new EventClassification();
    }

    /**
     * Create an instance of {@link EventStatusId }
     * 
     */
    public EventStatusId createEventStatusId() {
        return new EventStatusId();
    }

    /**
     * Create an instance of {@link EventStatus }
     * 
     */
    public EventStatus createEventStatus() {
        return new EventStatus();
    }

    /**
     * Create an instance of {@link EventAttributeId }
     * 
     */
    public EventAttributeId createEventAttributeId() {
        return new EventAttributeId();
    }

    /**
     * Create an instance of {@link EventAttribute }
     * 
     */
    public EventAttribute createEventAttribute() {
        return new EventAttribute();
    }

    /**
     * Create an instance of {@link DisciplineId }
     * 
     */
    public DisciplineId createDisciplineId() {
        return new DisciplineId();
    }

    /**
     * Create an instance of {@link Discipline }
     * 
     */
    public Discipline createDiscipline() {
        return new Discipline();
    }

    /**
     * Create an instance of {@link StartDate }
     * 
     */
    public StartDate createStartDate() {
        return new StartDate();
    }

    /**
     * Create an instance of {@link FinishDate }
     * 
     */
    public FinishDate createFinishDate() {
        return new FinishDate();
    }

    /**
     * Create an instance of {@link AlternativeDates }
     * 
     */
    public AlternativeDates createAlternativeDates() {
        return new AlternativeDates();
    }

    /**
     * Create an instance of {@link Sequence }
     * 
     */
    public Sequence createSequence() {
        return new Sequence();
    }

    /**
     * Create an instance of {@link EventOfficial }
     * 
     */
    public EventOfficial createEventOfficial() {
        return new EventOfficial();
    }

    /**
     * Create an instance of {@link EventOfficialId }
     * 
     */
    public EventOfficialId createEventOfficialId() {
        return new EventOfficialId();
    }

    /**
     * Create an instance of {@link EventRaceId }
     * 
     */
    public EventRaceId createEventRaceId() {
        return new EventRaceId();
    }

    /**
     * Create an instance of {@link EventRace }
     * 
     */
    public EventRace createEventRace() {
        return new EventRace();
    }

    /**
     * Create an instance of {@link RaceDate }
     * 
     */
    public RaceDate createRaceDate() {
        return new RaceDate();
    }

    /**
     * Create an instance of {@link RaceStatusId }
     * 
     */
    public RaceStatusId createRaceStatusId() {
        return new RaceStatusId();
    }

    /**
     * Create an instance of {@link RaceStatus }
     * 
     */
    public RaceStatus createRaceStatus() {
        return new RaceStatus();
    }

    /**
     * Create an instance of {@link EventCenterPosition }
     * 
     */
    public EventCenterPosition createEventCenterPosition() {
        return new EventCenterPosition();
    }

    /**
     * Create an instance of {@link Organiser }
     * 
     */
    public Organiser createOrganiser() {
        return new Organiser();
    }

    /**
     * Create an instance of {@link EventClass }
     * 
     */
    public EventClass createEventClass() {
        return new EventClass();
    }

    /**
     * Create an instance of {@link EventClassId }
     * 
     */
    public EventClassId createEventClassId() {
        return new EventClassId();
    }

    /**
     * Create an instance of {@link ClassShortName }
     * 
     */
    public ClassShortName createClassShortName() {
        return new ClassShortName();
    }

    /**
     * Create an instance of {@link EventClassStatus }
     * 
     */
    public EventClassStatus createEventClassStatus() {
        return new EventClassStatus();
    }

    /**
     * Create an instance of {@link ClassTypeId }
     * 
     */
    public ClassTypeId createClassTypeId() {
        return new ClassTypeId();
    }

    /**
     * Create an instance of {@link ClassType }
     * 
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link BaseClassId }
     * 
     */
    public BaseClassId createBaseClassId() {
        return new BaseClassId();
    }

    /**
     * Create an instance of {@link BaseClass }
     * 
     */
    public BaseClass createBaseClass() {
        return new BaseClass();
    }

    /**
     * Create an instance of {@link ExternalId }
     * 
     */
    public ExternalId createExternalId() {
        return new ExternalId();
    }

    /**
     * Create an instance of {@link ClassEntryFee }
     * 
     */
    public ClassEntryFee createClassEntryFee() {
        return new ClassEntryFee();
    }

    /**
     * Create an instance of {@link EntryFeeId }
     * 
     */
    public EntryFeeId createEntryFeeId() {
        return new EntryFeeId();
    }

    /**
     * Create an instance of {@link EntryFee }
     * 
     */
    public EntryFee createEntryFee() {
        return new EntryFee();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link PaidAmount }
     * 
     */
    public PaidAmount createPaidAmount() {
        return new PaidAmount();
    }

    /**
     * Create an instance of {@link ExternalFee }
     * 
     */
    public ExternalFee createExternalFee() {
        return new ExternalFee();
    }

    /**
     * Create an instance of {@link ValidFromDate }
     * 
     */
    public ValidFromDate createValidFromDate() {
        return new ValidFromDate();
    }

    /**
     * Create an instance of {@link ValidToDate }
     * 
     */
    public ValidToDate createValidToDate() {
        return new ValidToDate();
    }

    /**
     * Create an instance of {@link FromDateOfBirth }
     * 
     */
    public FromDateOfBirth createFromDateOfBirth() {
        return new FromDateOfBirth();
    }

    /**
     * Create an instance of {@link ToDateOfBirth }
     * 
     */
    public ToDateOfBirth createToDateOfBirth() {
        return new ToDateOfBirth();
    }

    /**
     * Create an instance of {@link PunchingUnitType }
     * 
     */
    public PunchingUnitType createPunchingUnitType() {
        return new PunchingUnitType();
    }

    /**
     * Create an instance of {@link ClassRaceInfo }
     * 
     */
    public ClassRaceInfo createClassRaceInfo() {
        return new ClassRaceInfo();
    }

    /**
     * Create an instance of {@link ClassRaceInfoId }
     * 
     */
    public ClassRaceInfoId createClassRaceInfoId() {
        return new ClassRaceInfoId();
    }

    /**
     * Create an instance of {@link CourseLength }
     * 
     */
    public CourseLength createCourseLength() {
        return new CourseLength();
    }

    /**
     * Create an instance of {@link ClassRaceStatus }
     * 
     */
    public ClassRaceStatus createClassRaceStatus() {
        return new ClassRaceStatus();
    }

    /**
     * Create an instance of {@link EntryBreak }
     * 
     */
    public EntryBreak createEntryBreak() {
        return new EntryBreak();
    }

    /**
     * Create an instance of {@link WebURL }
     * 
     */
    public WebURL createWebURL() {
        return new WebURL();
    }

    /**
     * Create an instance of {@link ContactData }
     * 
     */
    public ContactData createContactData() {
        return new ContactData();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link ServiceTypeId }
     * 
     */
    public ServiceTypeId createServiceTypeId() {
        return new ServiceTypeId();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link ServiceId }
     * 
     */
    public ServiceId createServiceId() {
        return new ServiceId();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link MaxNumber }
     * 
     */
    public MaxNumber createMaxNumber() {
        return new MaxNumber();
    }

    /**
     * Create an instance of {@link ServiceFee }
     * 
     */
    public ServiceFee createServiceFee() {
        return new ServiceFee();
    }

    /**
     * Create an instance of {@link ServiceFeeId }
     * 
     */
    public ServiceFeeId createServiceFeeId() {
        return new ServiceFeeId();
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link ServiceRequestId }
     * 
     */
    public ServiceRequestId createServiceRequestId() {
        return new ServiceRequestId();
    }

    /**
     * Create an instance of {@link PersonResult }
     * 
     */
    public PersonResult createPersonResult() {
        return new PersonResult();
    }

    /**
     * Create an instance of {@link ResultId }
     * 
     */
    public ResultId createResultId() {
        return new ResultId();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link StartNumber }
     * 
     */
    public StartNumber createStartNumber() {
        return new StartNumber();
    }

    /**
     * Create an instance of {@link BibNumber }
     * 
     */
    public BibNumber createBibNumber() {
        return new BibNumber();
    }

    /**
     * Create an instance of {@link CCardId }
     * 
     */
    public CCardId createCCardId() {
        return new CCardId();
    }

    /**
     * Create an instance of {@link CCard }
     * 
     */
    public CCard createCCard() {
        return new CCard();
    }

    /**
     * Create an instance of {@link StartTime }
     * 
     */
    public StartTime createStartTime() {
        return new StartTime();
    }

    /**
     * Create an instance of {@link FinishTime }
     * 
     */
    public FinishTime createFinishTime() {
        return new FinishTime();
    }

    /**
     * Create an instance of {@link Time }
     * 
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link TimeDiff }
     * 
     */
    public TimeDiff createTimeDiff() {
        return new TimeDiff();
    }

    /**
     * Create an instance of {@link ResultPosition }
     * 
     */
    public ResultPosition createResultPosition() {
        return new ResultPosition();
    }

    /**
     * Create an instance of {@link CompetitorStatus }
     * 
     */
    public CompetitorStatus createCompetitorStatus() {
        return new CompetitorStatus();
    }

    /**
     * Create an instance of {@link TeamSequence }
     * 
     */
    public TeamSequence createTeamSequence() {
        return new TeamSequence();
    }

    /**
     * Create an instance of {@link SplitTime }
     * 
     */
    public SplitTime createSplitTime() {
        return new SplitTime();
    }

    /**
     * Create an instance of {@link ControlCode }
     * 
     */
    public ControlCode createControlCode() {
        return new ControlCode();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link RaceResult }
     * 
     */
    public RaceResult createRaceResult() {
        return new RaceResult();
    }

    /**
     * Create an instance of {@link ServiceRequestFee }
     * 
     */
    public ServiceRequestFee createServiceRequestFee() {
        return new ServiceRequestFee();
    }

    /**
     * Create an instance of {@link RequestedQuantity }
     * 
     */
    public RequestedQuantity createRequestedQuantity() {
        return new RequestedQuantity();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link OrderedBy }
     * 
     */
    public OrderedBy createOrderedBy() {
        return new OrderedBy();
    }

    /**
     * Create an instance of {@link OrderedDate }
     * 
     */
    public OrderedDate createOrderedDate() {
        return new OrderedDate();
    }

    /**
     * Create an instance of {@link CreatedBy }
     * 
     */
    public CreatedBy createCreatedBy() {
        return new CreatedBy();
    }

    /**
     * Create an instance of {@link ValidRoles }
     * 
     */
    public ValidRoles createValidRoles() {
        return new ValidRoles();
    }

    /**
     * Create an instance of {@link ClassTypeComment }
     * 
     */
    public ClassTypeComment createClassTypeComment() {
        return new ClassTypeComment();
    }

    /**
     * Create an instance of {@link ParentEvent }
     * 
     */
    public ParentEvent createParentEvent() {
        return new ParentEvent();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link UserName }
     * 
     */
    public UserName createUserName() {
        return new UserName();
    }

    /**
     * Create an instance of {@link Password }
     * 
     */
    public Password createPassword() {
        return new Password();
    }

    /**
     * Create an instance of {@link ExternalPersonId }
     * 
     */
    public ExternalPersonId createExternalPersonId() {
        return new ExternalPersonId();
    }

    /**
     * Create an instance of {@link PreSelectedClass }
     * 
     */
    public PreSelectedClass createPreSelectedClass() {
        return new PreSelectedClass();
    }

    /**
     * Create an instance of {@link OrganisationList }
     * 
     */
    public OrganisationList createOrganisationList() {
        return new OrganisationList();
    }

    /**
     * Create an instance of {@link TeamMemberResult.TimeBehind }
     * 
     */
    public TeamMemberResult.TimeBehind createTeamMemberResultTimeBehind() {
        return new TeamMemberResult.TimeBehind();
    }

    /**
     * Create an instance of {@link TeamMemberResult.Position }
     * 
     */
    public TeamMemberResult.Position createTeamMemberResultPosition() {
        return new TeamMemberResult.Position();
    }

    /**
     * Create an instance of {@link OverallResult }
     * 
     */
    public OverallResult createOverallResult() {
        return new OverallResult();
    }

    /**
     * Create an instance of {@link TeamStatus }
     * 
     */
    public TeamStatus createTeamStatus() {
        return new TeamStatus();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link ActivityAttribute.Value }
     * 
     */
    public ActivityAttribute.Value createActivityAttributeValue() {
        return new ActivityAttribute.Value();
    }

    /**
     * Create an instance of {@link ActivityRegistration.AttributeValue }
     * 
     */
    public ActivityRegistration.AttributeValue createActivityRegistrationAttributeValue() {
        return new ActivityRegistration.AttributeValue();
    }

    /**
     * Create an instance of {@link ResponsibleOrganisationId }
     * 
     */
    public ResponsibleOrganisationId createResponsibleOrganisationId() {
        return new ResponsibleOrganisationId();
    }

    /**
     * Create an instance of {@link CompetitorList }
     * 
     */
    public CompetitorList createCompetitorList() {
        return new CompetitorList();
    }

    /**
     * Create an instance of {@link TeamContact }
     * 
     */
    public TeamContact createTeamContact() {
        return new TeamContact();
    }

    /**
     * Create an instance of {@link TeamCompetitor }
     * 
     */
    public TeamCompetitor createTeamCompetitor() {
        return new TeamCompetitor();
    }

    /**
     * Create an instance of {@link TeamCompetitorId }
     * 
     */
    public TeamCompetitorId createTeamCompetitorId() {
        return new TeamCompetitorId();
    }

    /**
     * Create an instance of {@link TeamOrder }
     * 
     */
    public TeamOrder createTeamOrder() {
        return new TeamOrder();
    }

    /**
     * Create an instance of {@link EntryEntryFee }
     * 
     */
    public EntryEntryFee createEntryEntryFee() {
        return new EntryEntryFee();
    }

    /**
     * Create an instance of {@link RoleTypeList }
     * 
     */
    public RoleTypeList createRoleTypeList() {
        return new RoleTypeList();
    }

    /**
     * Create an instance of {@link DeletedEventRaceList }
     * 
     */
    public DeletedEventRaceList createDeletedEventRaceList() {
        return new DeletedEventRaceList();
    }

    /**
     * Create an instance of {@link DeletedEventRace }
     * 
     */
    public DeletedEventRace createDeletedEventRace() {
        return new DeletedEventRace();
    }

    /**
     * Create an instance of {@link PersonServiceRequest }
     * 
     */
    public PersonServiceRequest createPersonServiceRequest() {
        return new PersonServiceRequest();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link EntryId }
     * 
     */
    public EntryId createEntryId() {
        return new EntryId();
    }

    /**
     * Create an instance of {@link TeamName }
     * 
     */
    public TeamName createTeamName() {
        return new TeamName();
    }

    /**
     * Create an instance of {@link EntryClass }
     * 
     */
    public EntryClass createEntryClass() {
        return new EntryClass();
    }

    /**
     * Create an instance of {@link AllocationControl }
     * 
     */
    public AllocationControl createAllocationControl() {
        return new AllocationControl();
    }

    /**
     * Create an instance of {@link AllocationControlType }
     * 
     */
    public AllocationControlType createAllocationControlType() {
        return new AllocationControlType();
    }

    /**
     * Create an instance of {@link EntryDate }
     * 
     */
    public EntryDate createEntryDate() {
        return new EntryDate();
    }

    /**
     * Create an instance of {@link CountryList }
     * 
     */
    public CountryList createCountryList() {
        return new CountryList();
    }

    /**
     * Create an instance of {@link MergedPersonList }
     * 
     */
    public MergedPersonList createMergedPersonList() {
        return new MergedPersonList();
    }

    /**
     * Create an instance of {@link MergedPerson }
     * 
     */
    public MergedPerson createMergedPerson() {
        return new MergedPerson();
    }

    /**
     * Create an instance of {@link EntryClassId }
     * 
     */
    public EntryClassId createEntryClassId() {
        return new EntryClassId();
    }

    /**
     * Create an instance of {@link ImportResultListResult }
     * 
     */
    public ImportResultListResult createImportResultListResult() {
        return new ImportResultListResult();
    }

    /**
     * Create an instance of {@link EventClassList }
     * 
     */
    public EventClassList createEventClassList() {
        return new EventClassList();
    }

    /**
     * Create an instance of {@link GeoObjectList }
     * 
     */
    public GeoObjectList createGeoObjectList() {
        return new GeoObjectList();
    }

    /**
     * Create an instance of {@link GeoObject }
     * 
     */
    public GeoObject createGeoObject() {
        return new GeoObject();
    }

    /**
     * Create an instance of {@link FinishPoint }
     * 
     */
    public FinishPoint createFinishPoint() {
        return new FinishPoint();
    }

    /**
     * Create an instance of {@link EntryFeeSequence }
     * 
     */
    public EntryFeeSequence createEntryFeeSequence() {
        return new EntryFeeSequence();
    }

    /**
     * Create an instance of {@link StatisticalResultRow }
     * 
     */
    public StatisticalResultRow createStatisticalResultRow() {
        return new StatisticalResultRow();
    }

    /**
     * Create an instance of {@link StatisticalResultColumn }
     * 
     */
    public StatisticalResultColumn createStatisticalResultColumn() {
        return new StatisticalResultColumn();
    }

    /**
     * Create an instance of {@link RouteCountList }
     * 
     */
    public RouteCountList createRouteCountList() {
        return new RouteCountList();
    }

    /**
     * Create an instance of {@link RouteCount }
     * 
     */
    public RouteCount createRouteCount() {
        return new RouteCount();
    }

    /**
     * Create an instance of {@link StartList }
     * 
     */
    public StartList createStartList() {
        return new StartList();
    }

    /**
     * Create an instance of {@link ClassStart }
     * 
     */
    public ClassStart createClassStart() {
        return new ClassStart();
    }

    /**
     * Create an instance of {@link PersonStart }
     * 
     */
    public PersonStart createPersonStart() {
        return new PersonStart();
    }

    /**
     * Create an instance of {@link Start }
     * 
     */
    public Start createStart() {
        return new Start();
    }

    /**
     * Create an instance of {@link StartId }
     * 
     */
    public StartId createStartId() {
        return new StartId();
    }

    /**
     * Create an instance of {@link RaceStart }
     * 
     */
    public RaceStart createRaceStart() {
        return new RaceStart();
    }

    /**
     * Create an instance of {@link TeamStart }
     * 
     */
    public TeamStart createTeamStart() {
        return new TeamStart();
    }

    /**
     * Create an instance of {@link TeamMemberStart }
     * 
     */
    public TeamMemberStart createTeamMemberStart() {
        return new TeamMemberStart();
    }

    /**
     * Create an instance of {@link DisciplineList }
     * 
     */
    public DisciplineList createDisciplineList() {
        return new DisciplineList();
    }

    /**
     * Create an instance of {@link OrganisationCompetitorCount }
     * 
     */
    public OrganisationCompetitorCount createOrganisationCompetitorCount() {
        return new OrganisationCompetitorCount();
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link ServiceList }
     * 
     */
    public ServiceList createServiceList() {
        return new ServiceList();
    }

    /**
     * Create an instance of {@link ActivityList }
     * 
     */
    public ActivityList createActivityList() {
        return new ActivityList();
    }

    /**
     * Create an instance of {@link ResultList }
     * 
     */
    public ResultList createResultList() {
        return new ResultList();
    }

    /**
     * Create an instance of {@link ClassResult }
     * 
     */
    public ClassResult createClassResult() {
        return new ClassResult();
    }

    /**
     * Create an instance of {@link TeamResult }
     * 
     */
    public TeamResult createTeamResult() {
        return new TeamResult();
    }

    /**
     * Create an instance of {@link EntryList }
     * 
     */
    public EntryList createEntryList() {
        return new EntryList();
    }

    /**
     * Create an instance of {@link MergedOrganisationList }
     * 
     */
    public MergedOrganisationList createMergedOrganisationList() {
        return new MergedOrganisationList();
    }

    /**
     * Create an instance of {@link MergedOrganisation }
     * 
     */
    public MergedOrganisation createMergedOrganisation() {
        return new MergedOrganisation();
    }

    /**
     * Create an instance of {@link ClassRaceInfoList }
     * 
     */
    public ClassRaceInfoList createClassRaceInfoList() {
        return new ClassRaceInfoList();
    }

    /**
     * Create an instance of {@link PersonServiceRequestList }
     * 
     */
    public PersonServiceRequestList createPersonServiceRequestList() {
        return new PersonServiceRequestList();
    }

    /**
     * Create an instance of {@link ClassCompetitorCount }
     * 
     */
    public ClassCompetitorCount createClassCompetitorCount() {
        return new ClassCompetitorCount();
    }

    /**
     * Create an instance of {@link StatisticalInquiryParam }
     * 
     */
    public StatisticalInquiryParam createStatisticalInquiryParam() {
        return new StatisticalInquiryParam();
    }

    /**
     * Create an instance of {@link StatisticalResult }
     * 
     */
    public StatisticalResult createStatisticalResult() {
        return new StatisticalResult();
    }

    /**
     * Create an instance of {@link PersonList }
     * 
     */
    public PersonList createPersonList() {
        return new PersonList();
    }

    /**
     * Create an instance of {@link BaseClassGroupList }
     * 
     */
    public BaseClassGroupList createBaseClassGroupList() {
        return new BaseClassGroupList();
    }

    /**
     * Create an instance of {@link BaseClassGroup }
     * 
     */
    public BaseClassGroup createBaseClassGroup() {
        return new BaseClassGroup();
    }

    /**
     * Create an instance of {@link BaseClassGroupId }
     * 
     */
    public BaseClassGroupId createBaseClassGroupId() {
        return new BaseClassGroupId();
    }

    /**
     * Create an instance of {@link RouteList }
     * 
     */
    public RouteList createRouteList() {
        return new RouteList();
    }

    /**
     * Create an instance of {@link ImportResponse }
     * 
     */
    public ImportResponse createImportResponse() {
        return new ImportResponse();
    }

    /**
     * Create an instance of {@link HashTableEntryList }
     * 
     */
    public HashTableEntryList createHashTableEntryList() {
        return new HashTableEntryList();
    }

    /**
     * Create an instance of {@link EventorApi.Position }
     * 
     */
    public EventorApi.Position createPosition() {
        return new EventorApi.Position();
    }

    /**
     * Create an instance of {@link EventAttributeList }
     * 
     */
    public EventAttributeList createEventAttributeList() {
        return new EventAttributeList();
    }

    /**
     * Create an instance of {@link OrganisationServiceRequestList }
     * 
     */
    public OrganisationServiceRequestList createOrganisationServiceRequestList() {
        return new OrganisationServiceRequestList();
    }

    /**
     * Create an instance of {@link OrganisationServiceRequest }
     * 
     */
    public OrganisationServiceRequest createOrganisationServiceRequest() {
        return new OrganisationServiceRequest();
    }

    /**
     * Create an instance of {@link CompetitorCountList }
     * 
     */
    public CompetitorCountList createCompetitorCountList() {
        return new CompetitorCountList();
    }

    /**
     * Create an instance of {@link CompetitorCount }
     * 
     */
    public CompetitorCount createCompetitorCount() {
        return new CompetitorCount();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link EventList }
     * 
     */
    public EventList createEventList() {
        return new EventList();
    }

    /**
     * Create an instance of {@link DocumentList }
     * 
     */
    public DocumentList createDocumentList() {
        return new DocumentList();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link ExternalLoginUrl }
     * 
     */
    public ExternalLoginUrl createExternalLoginUrl() {
        return new ExternalLoginUrl();
    }

    /**
     * Create an instance of {@link ResultListList }
     * 
     */
    public ResultListList createResultListList() {
        return new ResultListList();
    }

    /**
     * Create an instance of {@link EntryFeeList }
     * 
     */
    public EntryFeeList createEntryFeeList() {
        return new EntryFeeList();
    }

    /**
     * Create an instance of {@link LiveEventInformationList }
     * 
     */
    public LiveEventInformationList createLiveEventInformationList() {
        return new LiveEventInformationList();
    }

    /**
     * Create an instance of {@link LiveEventInformation }
     * 
     */
    public LiveEventInformation createLiveEventInformation() {
        return new LiveEventInformation();
    }

    /**
     * Create an instance of {@link StartListList }
     * 
     */
    public StartListList createStartListList() {
        return new StartListList();
    }

    /**
     * Create an instance of {@link StatisticalReport }
     * 
     */
    public StatisticalReport createStatisticalReport() {
        return new StatisticalReport();
    }

    /**
     * Create an instance of {@link OrganisationMembershipList }
     * 
     */
    public OrganisationMembershipList createOrganisationMembershipList() {
        return new OrganisationMembershipList();
    }

    /**
     * Create an instance of {@link OrganisationMemberships }
     * 
     */
    public OrganisationMemberships createOrganisationMemberships() {
        return new OrganisationMemberships();
    }

    /**
     * Create an instance of {@link EducationList }
     * 
     */
    public EducationList createEducationList() {
        return new EducationList();
    }

    /**
     * Create an instance of {@link Education }
     * 
     */
    public Education createEducation() {
        return new Education();
    }

    /**
     * Create an instance of {@link ServiceRequestList }
     * 
     */
    public ServiceRequestList createServiceRequestList() {
        return new ServiceRequestList();
    }

    /**
     * Create an instance of {@link ClassData }
     * 
     */
    public ClassData createClassData() {
        return new ClassData();
    }

    /**
     * Create an instance of {@link ImportStartListResult }
     * 
     */
    public ImportStartListResult createImportStartListResult() {
        return new ImportStartListResult();
    }

    /**
     * Create an instance of {@link MembershipType }
     * 
     */
    public MembershipType createMembershipType() {
        return new MembershipType();
    }

    /**
     * Create an instance of {@link Membership }
     * 
     */
    public Membership createMembership() {
        return new Membership();
    }

    /**
     * Create an instance of {@link LiveEventLink }
     * 
     */
    public LiveEventLink createLiveEventLink() {
        return new LiveEventLink();
    }

    /**
     * Create an instance of {@link EventorOrganisation }
     * 
     */
    public EventorOrganisation createEventorOrganisation() {
        return new EventorOrganisation();
    }

    /**
     * Create an instance of {@link EventorPerson }
     * 
     */
    public EventorPerson createEventorPerson() {
        return new EventorPerson();
    }

    /**
     * Create an instance of {@link ExternalLinks.Event.Race.Link }
     * 
     */
    public ExternalLinks.Event.Race.Link createExternalLinksEventRaceLink() {
        return new ExternalLinks.Event.Race.Link();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TimeMode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTimeMode(String value) {
        return new JAXBElement<String>(_TimeMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RouteCount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RouteCount")
    public JAXBElement<RouteCount> createRouteCount(RouteCount value) {
        return new JAXBElement<RouteCount>(_RouteCount_QNAME, RouteCount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Information")
    public JAXBElement<String> createInformation(String value) {
        return new JAXBElement<String>(_Information_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Route }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Route")
    public JAXBElement<Route> createRoute(Route value) {
        return new JAXBElement<Route>(_Route_QNAME, Route.class, null, value);
    }

}
