//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.03 at 09:33:02 PM AEDT 
//


package EventorApi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TeamName"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}OrganisationId"/>
 *           &lt;element ref="{}Organisation"/>
 *           &lt;element ref="{}CountryId"/>
 *           &lt;element ref="{}Country"/>
 *         &lt;/choice>
 *         &lt;element ref="{}BibNumber" minOccurs="0"/>
 *         &lt;element ref="{}StartTime" minOccurs="0"/>
 *         &lt;element ref="{}FinishTime" minOccurs="0"/>
 *         &lt;element ref="{}Time" minOccurs="0"/>
 *         &lt;element ref="{}TimeDiff" minOccurs="0"/>
 *         &lt;element ref="{}ResultPosition" minOccurs="0"/>
 *         &lt;element ref="{}TeamStatus"/>
 *         &lt;element ref="{}Point" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}TeamMemberResult" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "teamName",
    "organisationIdOrOrganisationOrCountryId",
    "bibNumber",
    "startTime",
    "finishTime",
    "time",
    "timeDiff",
    "resultPosition",
    "teamStatus",
    "point",
    "teamMemberResult"
})
@XmlRootElement(name = "TeamResult")
public class TeamResult {

    @XmlElement(name = "TeamName", required = true)
    protected TeamName teamName;
    @XmlElements({
        @XmlElement(name = "OrganisationId", type = OrganisationId.class),
        @XmlElement(name = "Organisation", type = Organisation.class),
        @XmlElement(name = "CountryId", type = CountryId.class),
        @XmlElement(name = "Country", type = Country.class)
    })
    protected List<Object> organisationIdOrOrganisationOrCountryId;
    @XmlElement(name = "BibNumber")
    protected BibNumber bibNumber;
    @XmlElement(name = "StartTime")
    protected StartTime startTime;
    @XmlElement(name = "FinishTime")
    protected FinishTime finishTime;
    @XmlElement(name = "Time")
    protected Time time;
    @XmlElement(name = "TimeDiff")
    protected TimeDiff timeDiff;
    @XmlElement(name = "ResultPosition")
    protected ResultPosition resultPosition;
    @XmlElement(name = "TeamStatus", required = true)
    protected TeamStatus teamStatus;
    @XmlElement(name = "Point")
    protected List<Point> point;
    @XmlElement(name = "TeamMemberResult")
    protected List<TeamMemberResult> teamMemberResult;

    /**
     * Gets the value of the teamName property.
     * 
     * @return
     *     possible object is
     *     {@link TeamName }
     *     
     */
    public TeamName getTeamName() {
        return teamName;
    }

    /**
     * Sets the value of the teamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamName }
     *     
     */
    public void setTeamName(TeamName value) {
        this.teamName = value;
    }

    /**
     * Gets the value of the organisationIdOrOrganisationOrCountryId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organisationIdOrOrganisationOrCountryId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganisationIdOrOrganisationOrCountryId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganisationId }
     * {@link Organisation }
     * {@link CountryId }
     * {@link Country }
     * 
     * 
     */
    public List<Object> getOrganisationIdOrOrganisationOrCountryId() {
        if (organisationIdOrOrganisationOrCountryId == null) {
            organisationIdOrOrganisationOrCountryId = new ArrayList<Object>();
        }
        return this.organisationIdOrOrganisationOrCountryId;
    }

    /**
     * Gets the value of the bibNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BibNumber }
     *     
     */
    public BibNumber getBibNumber() {
        return bibNumber;
    }

    /**
     * Sets the value of the bibNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibNumber }
     *     
     */
    public void setBibNumber(BibNumber value) {
        this.bibNumber = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link StartTime }
     *     
     */
    public StartTime getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartTime }
     *     
     */
    public void setStartTime(StartTime value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the finishTime property.
     * 
     * @return
     *     possible object is
     *     {@link FinishTime }
     *     
     */
    public FinishTime getFinishTime() {
        return finishTime;
    }

    /**
     * Sets the value of the finishTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinishTime }
     *     
     */
    public void setFinishTime(FinishTime value) {
        this.finishTime = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link Time }
     *     
     */
    public Time getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link Time }
     *     
     */
    public void setTime(Time value) {
        this.time = value;
    }

    /**
     * Gets the value of the timeDiff property.
     * 
     * @return
     *     possible object is
     *     {@link TimeDiff }
     *     
     */
    public TimeDiff getTimeDiff() {
        return timeDiff;
    }

    /**
     * Sets the value of the timeDiff property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeDiff }
     *     
     */
    public void setTimeDiff(TimeDiff value) {
        this.timeDiff = value;
    }

    /**
     * Gets the value of the resultPosition property.
     * 
     * @return
     *     possible object is
     *     {@link ResultPosition }
     *     
     */
    public ResultPosition getResultPosition() {
        return resultPosition;
    }

    /**
     * Sets the value of the resultPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultPosition }
     *     
     */
    public void setResultPosition(ResultPosition value) {
        this.resultPosition = value;
    }

    /**
     * Gets the value of the teamStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TeamStatus }
     *     
     */
    public TeamStatus getTeamStatus() {
        return teamStatus;
    }

    /**
     * Sets the value of the teamStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamStatus }
     *     
     */
    public void setTeamStatus(TeamStatus value) {
        this.teamStatus = value;
    }

    /**
     * Gets the value of the point property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the point property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Point }
     * 
     * 
     */
    public List<Point> getPoint() {
        if (point == null) {
            point = new ArrayList<Point>();
        }
        return this.point;
    }

    /**
     * Gets the value of the teamMemberResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the teamMemberResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTeamMemberResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TeamMemberResult }
     * 
     * 
     */
    public List<TeamMemberResult> getTeamMemberResult() {
        if (teamMemberResult == null) {
            teamMemberResult = new ArrayList<TeamMemberResult>();
        }
        return this.teamMemberResult;
    }

}
